### ISSUE TITLE
`container` component doesn't use the legacy `SlottedItem` structure

### ISSUE THREAD

**Issue by MulverineX** [SpyglassMC/vanilla-mcdoc#35] opened 2024-07-05 17:52 UTC
`id` -> `item`
`Slot` -> `slot`

TODO: Determine whether this affects other places and whether this was in 1.20.5 or 1.21.

**Comment by its-brody** [comment] 2024-07-30 17:36
bump?

**Comment by MulverineX** [comment] 2024-07-30 17:39
If you have the time I'd appreciate some info on what's stated in this issue description, then it'd be a lot easier to handle fixing this.

**Comment by its-brody** [comment] 2024-07-30 17:42
In my duplicate of this issue I have some screen shots of the errors. Not quite sure what you are asking for. It just seems that the it thinks its a error/problem when its how the commands are meant to be typed. Are you wanting the minecraft commands I used to get the errors?

**Comment by MulverineX** [comment] 2024-07-30 17:44
> TODO: Determine whether this affects other places and whether this was in 1.20.5 or 1.21.

1. Are there any other data components or NBT locations where this change in format occured?
2. Did this change occur in 1.20.5 or 1.21?

**Comment by its-brody** [comment] 2024-07-30 17:51
1. No idea I only noticed in my case.
2. I can only confirm 1.21. (the current version of minecraft)

Here is an example of the command I used `give @p chest[container=[{slot:0,item:{id:"minecraft:stone",count:1}}]] 1`

**Closed** 2024-08-08 17:52 UTC
Labels: bug
